### ISSUE TITLE
wwhrd misidentifies ISC license in go-spew as 0BSD

### ISSUE THREAD

**Issue by TBBle** [frapposelli/wwhrd#40] opened 2020-11-15 15:49 UTC
Observed in https://github.com/docker/compose-on-kubernetes, for some reason the vendored [LICENSE](https://github.com/docker/compose-on-kubernetes/blob/master/vendor/github.com/davecgh/go-spew/LICENSE) from go-spew 1.1.1:

> Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

is being recognised as [0BSD](https://spdx.org/licenses/0BSD):
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.

instead of [ISC](https://spdx.org/licenses/ISC):
> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

Unlike #18 it's definitely finding _a_ license, but reporting the wrong one.

[pkg.go.dev](https://pkg.go.dev/github.com/davecgh/go-spew/spew?tab=licenses) detects it correctly as ISC.

wwhrd Version:
```
version dev
commit 1961213
date 1961-02-13T20:06:35Z
```

I don't know where version numbering comes from, but the checkout in my go/src/github.com/frapposelli/wwhrd directory is 749cb0f413602c9a4992cbeeb3d125ac325d9a30

**Comment by frapposelli** [comment] 2020-11-17 10:59
Hi @TBBle I've looked at the problem and can definitely reproduce. 

The issue at hand is that the license-detector library gives the `go-spew` license a 93% probability of being `0BSD` and 84% of being `ISC`.

`wwhrd` takes the best result and uses it. Not sure why it's being misidentified but I've had similar troubles in the past with this package in particular, I'll dig deeper and file an issue on go-spew if needed.

**Comment by TBBle** [comment] 2020-11-17 13:17
The only other thing I noticed is that the Go source files are still missing the "/or" for which #18 was filed. But I am assuming the library doesn't look at them, as that would equally mismatch 0BSD and ISC.

**Comment by frapposelli** [comment] 2020-11-17 16:19
I went spelunking in my history, looks like the previous license detector library was content with the `/or` fix which was added here davecgh/go-spew@e250ec7f597aa5cd2c9f38b9cbf3dbc81cc1e3bb

The new library is using a different, more holistic approach, so I wouldn't be surprised if it evaluates other files and not just `LICENSE`. I'll try a fix in the coming days and send out a PR to davecgh/go-spew if it solves the problem 😄

**Comment by frapposelli** [comment] 2020-11-24 10:26
Hi @TBBle, I've just cut version `v0.3.1` but your issue hasn't been fixed by the library update.

Looks like the library has changed hands now, I've opened an issue in the new repo (go-enry/go-license-detector#4). I'll keep this one open until we get to the bottom of it.

**Closed** 2020-12-08 19:21 UTC
