### ISSUE TITLE
go get -u fails

### ISSUE THREAD

**Issue by demyxco** [frapposelli/wwhrd#35] opened 2020-01-11 02:08 UTC
```
go get -u github.com/frapposelli/wwhrd         
go: finding github.com/frapposelli/wwhrd v0.3.0
go: downloading github.com/frapposelli/wwhrd v0.3.0
go: extracting github.com/frapposelli/wwhrd v0.3.0
go: downloading github.com/cloudfoundry-incubator/candiedyaml v0.0.0-20170223024657-cff29b469e0f
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading gopkg.in/src-d/go-license-detector.v3 v3.0.2
go: extracting github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/emicklei/dot v0.10.1
go: extracting github.com/cloudfoundry-incubator/candiedyaml v0.0.0-20170223024657-cff29b469e0f
go: extracting github.com/emicklei/dot v0.10.1
go: extracting gopkg.in/src-d/go-license-detector.v3 v3.0.2
go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
go: extracting gopkg.in/src-d/go-git.v4 v4.13.1
go: downloading gopkg.in/src-d/go-billy.v4 v4.3.2
go: downloading gopkg.in/src-d/go-billy-siva.v4 v4.3.0
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/jdkato/prose v1.1.0
go: extracting gopkg.in/src-d/go-billy.v4 v4.3.2
go: downloading gonum.org/v1/gonum v0.6.1
go: extracting gopkg.in/src-d/go-billy-siva.v4 v4.3.0
go: extracting github.com/emirpasic/gods v1.12.0
go: downloading github.com/russross/blackfriday v1.5.2
go: downloading gopkg.in/src-d/go-siva.v1 v1.5.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/russross/blackfriday v1.5.2
go: extracting gopkg.in/src-d/go-siva.v1 v1.5.0
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading golang.org/x/exp v0.0.0-20190125153040-c74c464bbbf2
go: extracting github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95
go: extracting github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95
go: extracting golang.org/x/exp v0.0.0-20190125153040-c74c464bbbf2
go: extracting github.com/jdkato/prose v1.1.0
go: extracting gonum.org/v1/gonum v0.6.1
go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: extracting github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: downloading github.com/ekzhu/minhash-lsh v0.0.0-20171225071031-5c06ee8586a1
go: downloading github.com/hhatto/gorst v0.0.0-20171128071645-7682c8a25108
go: extracting github.com/ekzhu/minhash-lsh v0.0.0-20171225071031-5c06ee8586a1
go: extracting github.com/hhatto/gorst v0.0.0-20171128071645-7682c8a25108
go: downloading github.com/xanzy/ssh-agent v0.2.1
go: downloading github.com/shogo82148/go-shuffle v0.0.0-20170808115208-59829097ff3b
go: extracting github.com/xanzy/ssh-agent v0.2.1
go: downloading github.com/src-d/gcfg v1.4.0
go: extracting github.com/shogo82148/go-shuffle v0.0.0-20170808115208-59829097ff3b
go: downloading gopkg.in/neurosnap/sentences.v1 v1.0.6
go: extracting github.com/src-d/gcfg v1.4.0
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading github.com/dgryski/go-minhash v0.0.0-20170608043002-7fe510aff544
go: extracting github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: extracting github.com/dgryski/go-minhash v0.0.0-20170608043002-7fe510aff544
go: extracting gopkg.in/neurosnap/sentences.v1 v1.0.6
go: downloading github.com/montanaflynn/stats v0.0.0-20151014174947-eeaced052adb
go: extracting github.com/montanaflynn/stats v0.0.0-20151014174947-eeaced052adb
go: downloading gopkg.in/warnings.v0 v0.1.2
go: extracting gopkg.in/warnings.v0 v0.1.2
go: finding gopkg.in/src-d/go-billy.v4 v4.3.2
go: finding golang.org/x/exp latest
go: finding github.com/montanaflynn/stats v0.5.0
go: finding github.com/jessevdk/go-flags v1.4.0
go: finding github.com/shogo82148/go-shuffle latest
go: finding github.com/jbenet/go-context latest
go: finding golang.org/x/crypto latest
go: finding github.com/sergi/go-diff v1.1.0
go: finding gonum.org/v1/gonum v0.6.2
go: finding gopkg.in/src-d/go-siva.v1 v1.8.0
go: finding golang.org/x/net latest
go: finding github.com/src-d/gcfg v1.4.0
go: finding github.com/jdkato/prose v1.1.1
go: finding golang.org/x/sys latest
go: finding gopkg.in/src-d/go-billy-siva.v4 v4.6.0
go: finding github.com/dgryski/go-minhash latest
go: finding gopkg.in/src-d/go-git.v4 v4.13.1
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/kevinburke/ssh_config latest
go: finding gopkg.in/neurosnap/sentences.v1 v1.0.6
go: finding github.com/hhatto/gorst latest
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/emirpasic/gods v1.12.0
go: finding github.com/russross/blackfriday/v2 v2.0.1
go: finding gopkg.in/src-d/go-license-detector.v3 v3.0.2
go: finding github.com/emicklei/dot v0.10.1
go: finding github.com/ekzhu/minhash-lsh latest
go: finding github.com/xanzy/ssh-agent v0.2.1
go: finding github.com/cloudfoundry-incubator/candiedyaml latest
go: downloading github.com/cloudfoundry-incubator/candiedyaml v0.0.0-20170901234223-a41693b7b7af
go: extracting github.com/cloudfoundry-incubator/candiedyaml v0.0.0-20170901234223-a41693b7b7af
go: downloading gopkg.in/src-d/go-billy-siva.v4 v4.6.0
go: downloading github.com/jdkato/prose v1.1.1
go: extracting gopkg.in/src-d/go-billy-siva.v4 v4.6.0
go: downloading golang.org/x/crypto v0.0.0-20200109152110-61a87790db17
go: downloading github.com/sergi/go-diff v1.1.0
go: extracting github.com/sergi/go-diff v1.1.0
go: downloading github.com/ekzhu/minhash-lsh v0.0.0-20190924033628-faac2c6342f8
go: extracting golang.org/x/crypto v0.0.0-20200109152110-61a87790db17
go: extracting github.com/ekzhu/minhash-lsh v0.0.0-20190924033628-faac2c6342f8
go: downloading gopkg.in/src-d/go-siva.v1 v1.8.0
go: extracting github.com/jdkato/prose v1.1.1
go: extracting gopkg.in/src-d/go-siva.v1 v1.8.0
go: downloading github.com/dgryski/go-minhash v0.0.0-20190315135803-ad340ca03076
go: downloading github.com/hhatto/gorst v0.0.0-20181029133204-ca9f730cac5b
go: extracting github.com/dgryski/go-minhash v0.0.0-20190315135803-ad340ca03076
go: extracting github.com/hhatto/gorst v0.0.0-20181029133204-ca9f730cac5b
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/shogo82148/go-shuffle v0.0.0-20180218125048-27e6095f230d
go: extracting github.com/montanaflynn/stats v0.5.0
go: extracting github.com/shogo82148/go-shuffle v0.0.0-20180218125048-27e6095f230d
go: downloading golang.org/x/exp v0.0.0-20191227195350-da58074b4299
go: downloading gonum.org/v1/gonum v0.6.2
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting github.com/shurcooL/sanitized_anchor_name v1.0.0
go: extracting golang.org/x/exp v0.0.0-20191227195350-da58074b4299
go: extracting gonum.org/v1/gonum v0.6.2
# gopkg.in/src-d/go-license-detector.v3/licensedb/internal
../../pkg/mod/gopkg.in/src-d/go-license-detector.v3@v3.0.2/licensedb/internal/db.go:224:37: not enough arguments in call to minhashlsh.NewMinhashLSH64
        have (number, number)
        want (int, float64, int)
```

**Comment by frapposelli** [comment] 2020-01-11 16:31
interesting, looks like a problem with `go.mod` in one of the dependencies. working on a fix

**Comment by samurnin** [comment] 2020-03-27 19:43
I also got the same issue:
go get -u github.com/frapposelli/wwhrd
go: github.com/pkg/errors upgrade => v0.9.1
go: golang.org/x/sys upgrade => v0.0.0-20200327173247-9dae0f8f5775
go: gopkg.in/src-d/go-license-detector.v3 upgrade => v3.1.0
go: github.com/sirupsen/logrus upgrade => v1.5.0
go: github.com/ekzhu/minhash-lsh upgrade => v0.0.0-20190924033628-faac2c6342f8
go: golang.org/x/net upgrade => v0.0.0-20200324143707-d3edc9973b7e
go: github.com/shogo82148/go-shuffle upgrade => v0.0.0-20180218125048-27e6095f230d
go: github.com/dgryski/go-minhash upgrade => v0.0.0-20190315135803-ad340ca03076
go: github.com/cloudfoundry-incubator/candiedyaml upgrade => v0.0.0-20170901234223-a41693b7b7af
go: github.com/montanaflynn/stats upgrade => v0.6.3
go: github.com/emicklei/dot upgrade => v0.10.2
go: golang.org/x/text upgrade => v0.3.2
go: gopkg.in/src-d/go-billy-siva.v4 upgrade => v4.6.0
go: github.com/hhatto/gorst upgrade => v0.0.0-20181029133204-ca9f730cac5b
go: golang.org/x/exp upgrade => v0.0.0-20200320212757-167ffe94c325
go: gopkg.in/src-d/go-siva.v1 upgrade => v1.8.0
go: golang.org/x/crypto upgrade => v0.0.0-20200323165209-0ec3e9974c59
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.2
go: gonum.org/v1/gonum upgrade => v0.7.0
go: github.com/shurcooL/sanitized_anchor_name upgrade => v1.0.0
go: github.com/sergi/go-diff upgrade => v1.1.0
go: github.com/jdkato/prose upgrade => v1.1.1
# gopkg.in/src-d/go-license-detector.v3/licensedb/internal
C:\Users\samur\go\pkg\mod\gopkg.in\src-d\go-license-detector.v3@v3.1.0\licensedb\internal\db.go:224:37: not enough arguments in call to minhashlsh.NewMinhashLSH64
        have (number, number)
        want (int, float64, int)

**Comment by frapposelli** [comment] 2020-11-17 10:22
This should've been fixed by now, I've just tried to reproduce with:

```console
$ docker run --rm -it golang:latest go get -v github.com/frapposelli/wwhrd
github.com/frapposelli/wwhrd (download)
github.com/frapposelli/wwhrd/vendor/golang.org/x/crypto/internal/subtle
github.com/frapposelli/wwhrd/vendor/golang.org/x/net/html/atom
github.com/frapposelli/wwhrd/vendor/gonum.org/v1/gonum/blas
[...]
github.com/frapposelli/wwhrd/vendor/gopkg.in/src-d/go-license-detector.v3/licensedb/internal
github.com/frapposelli/wwhrd/vendor/gopkg.in/src-d/go-license-detector.v3/licensedb
github.com/frapposelli/wwhrd
$ echo $?
0
```

I'm going to close the issue but please let me know if this happens again.

**Closed by frapposelli** 2020-11-17 10:22 UTC
